# Generated by Django 3.2.1 on 2021-05-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_suscriptores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptores',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
