# Generated by Django 3.2.1 on 2021-06-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_suscriptores_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.CharField(choices=[['CO', 'consulta'], ['RE', 'reclamo'], ['SU', 'sugerencia'], ['FE', 'felitaciones']], max_length=3),
        ),
    ]
