# Generated by Django 3.2.1 on 2021-06-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nuevo',
        ),
    ]
